title: Tezos Snapshots
author: Oxhead Alpha
description: > # this means to ignore newlines until "show_excerpts:"
  Tezos Snapshots
favicon: "./favicon.ico" # set the favicon of the site
show_excerpts: false # set to true to show excerpts on the homepage
# url becomes localhost in development environments
url: https://xtz-shots.io
domain_name: xtz-shots.io

# Theme settings
doks:
  baseurl:
  color_theme: blue # Available themes: blue (default), green, purple, red and yellow
  header:
    logo:
      text: XTZ-Shots
      image:
      logo_url: "https://xtz-shots.io"

  footer:
    content:
      logo:
        text: XTZ-Shots
        image:
      copyright: Copyright &copy; 2022. - Oxhead Alpha <br>All rights reserved.
    social_list:
      - network_name: github
        profile_url: "https://github.com/oxheadalpha"
      - network_name: twitter
        profile_url: "https://twitter.com/oxheadalpha"
      - network_name: sphere
        profile_url: "https://www.oxheadalpha.com"
  google_analytics:
    tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
  comments:
    disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
  sass_dir: ./_sass
  style: :compressed

# Jekyll settings
layouts_dir: ./_layouts
includes_dir: ./_includes
exclude: ["README.md", "CHANGELOG.md", "bundle/"]
permalink: /:title/

plugins:
  - jekyll-datapage-generator

page_gen-dirs: true
page_gen:
- data: snapshot_jekyll_data.latest_snapshots
  template: latest_snapshots
  debug: true
  name: "name"
  dir: "latest"
  extension: "md"
- data: snapshot_jekyll_data.all_snapshots
  template: all_snapshots
  debug: true
  name: "name"
  dir: "all"
  extension: "md"
